#!/bin/bash

#
# runs stress tester with correct parameters.
#

if [ $# -lt 5 ]; then
    echo "Usage: $0 -s=\"<path to stress.exe>\" -b=<batch size> -u=<user count to simulate> -r=<rpc throughput> -c=\"<simulate-config.cfg>\""
    exit 1
fi

path=""
batch_size=0
user_count=0
user_index=0
throughput=1
rpc_delay=0
config=""

if [ "${1:0:3}" = "-s=" ]; then
    path="${1:3}"
fi
if [ "${2:0:3}" = "-b=" ]; then
    batch_size=${2:3}
fi
if [ "${3:0:3}" = "-u=" ]; then
    user_count=${3:3}
fi
if [ "${4:0:3}" = "-r=" ]; then
    throughput=${4:3}
fi
if [ "${5:0:3}" = "-c=" ]; then
    config="${5:3}"
fi
rpc_delay=$(( $batch_size *1000 / $throughput ))
while [ $user_index -lt $user_count ]
do
    cmd="$path -DNUM_CONNECTIONS=$batch_size -DSTART_INDEX=$user_index -DRPC_DELAY=$rpc_delay -c $config"
    echo "$cmd"
    $cmd
    user_index=$(( $batch_size+$user_index ))
done
